export type Word = {
  word: string
  spy: string[]
}
const words: Word[] = [
  { word: 'pomme', spy: ['banane', 'poire', 'raisin'] },
  { word: 'banane', spy: ['pomme', 'poire', 'raisin'] },
  { word: 'poire', spy: ['pomme', 'banane', 'raisin'] },
  { word: 'raisin', spy: ['pomme', 'banane', 'poire'] },
  { word: 'avion', spy: ['pilote', 'aéroport', 'vol'] },
  { word: 'pilote', spy: ['avion', 'aéroport', 'vol'] },
  { word: 'aéroport', spy: ['avion', 'pilote', 'vol'] },
  { word: 'vol', spy: ['avion', 'pilote', 'aéroport'] },
  { word: 'école', spy: ['élève', 'professeur', 'classe'] },
  { word: 'élève', spy: ['école', 'professeur', 'classe'] },
  { word: 'professeur', spy: ['école', 'élève', 'classe'] },
  { word: 'classe', spy: ['école', 'élève', 'professeur'] },
  { word: 'ordinateur', spy: ['clavier', 'écran', 'souris'] },
  { word: 'clavier', spy: ['ordinateur', 'écran', 'souris'] },
  { word: 'écran', spy: ['ordinateur', 'clavier', 'souris'] },
  { word: 'souris', spy: ['ordinateur', 'clavier', 'écran'] },
  { word: 'guitare', spy: ['musique', 'cordes', 'instrument'] },
  { word: 'musique', spy: ['guitare', 'cordes', 'instrument'] },
  { word: 'cordes', spy: ['guitare', 'musique', 'instrument'] },
  { word: 'instrument', spy: ['guitare', 'musique', 'cordes'] },
  { word: 'montagne', spy: ['sommet', 'randonnée', 'alpinisme'] },
  { word: 'sommet', spy: ['montagne', 'randonnée', 'alpinisme'] },
  { word: 'randonnée', spy: ['montagne', 'sommet', 'alpinisme'] },
  { word: 'alpinisme', spy: ['montagne', 'sommet', 'randonnée'] },
  { word: 'peinture', spy: ['art', 'toile', 'pinceau'] },
  { word: 'art', spy: ['peinture', 'toile', 'pinceau'] },
  { word: 'toile', spy: ['peinture', 'art', 'pinceau'] },
  { word: 'pinceau', spy: ['peinture', 'art', 'toile'] },
  { word: 'voiture', spy: ['moteur', 'route', 'conduite'] },
  { word: 'moteur', spy: ['voiture', 'route', 'conduite'] },
  { word: 'route', spy: ['voiture', 'moteur', 'conduite'] },
  { word: 'conduite', spy: ['voiture', 'moteur', 'route'] },
  { word: 'téléphone', spy: ['appel', 'portable', 'communication'] },
  { word: 'appel', spy: ['téléphone', 'portable', 'communication'] },
  { word: 'portable', spy: ['téléphone', 'appel', 'communication'] },
  { word: 'communication', spy: ['téléphone', 'appel', 'portable'] },
  { word: 'cinéma', spy: ['film', 'écran', 'acteur'] },
  { word: 'film', spy: ['cinéma', 'écran', 'acteur'] },
  { word: 'écran', spy: ['cinéma', 'film', 'acteur'] },
  { word: 'acteur', spy: ['cinéma', 'film', 'écran'] },
  { word: 'jardin', spy: ['fleurs', 'plantes', 'potager'] },
  { word: 'fleurs', spy: ['jardin', 'plantes', 'potager'] },
  { word: 'plantes', spy: ['jardin', 'fleurs', 'potager'] },
  { word: 'potager', spy: ['jardin', 'fleurs', 'plantes'] },
  { word: 'hôpital', spy: ['médecin', 'infirmière', 'patient'] },
  { word: 'médecin', spy: ['hôpital', 'infirmière', 'patient'] },
  { word: 'infirmière', spy: ['hôpital', 'médecin', 'patient'] },
  { word: 'patient', spy: ['hôpital', 'médecin', 'infirmière'] },
  { word: 'restaurant', spy: ['menu', 'serveur', 'cuisine'] },
  { word: 'menu', spy: ['restaurant', 'serveur', 'cuisine'] },
  { word: 'serveur', spy: ['restaurant', 'menu', 'cuisine'] },
  { word: 'cuisine', spy: ['restaurant', 'menu', 'serveur'] },
  { word: 'bibliothèque', spy: ['livres', 'lecture', 'étagères'] },
  { word: 'livres', spy: ['bibliothèque', 'lecture', 'étagères'] },
  { word: 'lecture', spy: ['bibliothèque', 'livres', 'étagères'] },
  { word: 'étagères', spy: ['bibliothèque', 'livres', 'lecture'] },
  { word: 'plage', spy: ['sable', 'mer', 'soleil'] },
  { word: 'sable', spy: ['plage', 'mer', 'soleil'] },
  { word: 'mer', spy: ['plage', 'sable', 'soleil'] },
  { word: 'soleil', spy: ['plage', 'sable', 'mer'] },
  { word: 'football', spy: ['ballon', 'but', 'équipe'] },
  { word: 'ballon', spy: ['football', 'but', 'équipe'] },
  { word: 'but', spy: ['football', 'ballon', 'équipe'] },
  { word: 'équipe', spy: ['football', 'ballon', 'but'] },
  { word: 'théâtre', spy: ['scène', 'acteur', 'pièce'] },
  { word: 'scène', spy: ['théâtre', 'acteur', 'pièce'] },
  { word: 'acteur', spy: ['théâtre', 'scène', 'pièce'] },
  { word: 'pièce', spy: ['théâtre', 'scène', 'acteur'] },
  { word: 'astronomie', spy: ['étoiles', 'planète', 'télescope'] },
  { word: 'étoiles', spy: ['astronomie', 'planète', 'télescope'] },
  { word: 'planète', spy: ['astronomie', 'étoiles', 'télescope'] },
  { word: 'télescope', spy: ['astronomie', 'étoiles', 'planète'] },
  { word: 'cuisine', spy: ['recette', 'ingrédients', 'chef'] },
  { word: 'recette', spy: ['cuisine', 'ingrédients', 'chef'] },
  { word: 'ingrédients', spy: ['cuisine', 'recette', 'chef'] },
  { word: 'chef', spy: ['cuisine', 'recette', 'ingrédients'] },
  { word: 'photographie', spy: ['appareil', 'image', 'objectif'] },
  { word: 'appareil', spy: ['photographie', 'image', 'objectif'] },
  { word: 'image', spy: ['photographie', 'appareil', 'objectif'] },
  { word: 'objectif', spy: ['photographie', 'appareil', 'image'] },
  { word: 'danse', spy: ['ballet', 'mouvement', 'musique'] },
  { word: 'ballet', spy: ['danse', 'mouvement', 'musique'] },
  { word: 'mouvement', spy: ['danse', 'ballet', 'musique'] },
  { word: 'musique', spy: ['danse', 'ballet', 'mouvement'] },
  { word: 'vélo', spy: ['pédales', 'guidon', 'cycliste'] },
  { word: 'pédales', spy: ['vélo', 'guidon', 'cycliste'] },
  { word: 'guidon', spy: ['vélo', 'pédales', 'cycliste'] },
  { word: 'cycliste', spy: ['vélo', 'pédales', 'guidon'] },
  { word: 'zoo', spy: ['animaux', 'enclos', 'visite'] },
  { word: 'animaux', spy: ['zoo', 'enclos', 'visite'] },
  { word: 'enclos', spy: ['zoo', 'animaux', 'visite'] },
  { word: 'visite', spy: ['zoo', 'animaux', 'enclos'] },
  { word: 'notes', spy: ['mélodie', 'orchestre', 'musique'] },
  { word: 'mélodie', spy: ['notes', 'orchestre', 'musique'] },
  { word: 'orchestre', spy: ['notes', 'mélodie', 'musique'] },
  { word: 'Télescope', spy: ['Galaxie'] },
  { word: 'Galaxie', spy: ['Télescope'] },
  { word: 'Ombre', spy: ['Silhouettes', 'Crépuscule', 'Reflet'] },
  { word: 'Silhouettes', spy: ['Ombre', 'Crépuscule', 'Reflet'] },
  { word: 'Crépuscule', spy: ['Ombre', 'Silhouettes', 'Reflet'] },
  { word: 'Reflet', spy: ['Ombre', 'Silhouettes', 'Crépuscule'] },
  { word: 'Écho', spy: ['Réverbération', 'Répétition', 'Son'] },
  { word: 'Réverbération', spy: ['Écho', 'Répétition', 'Son'] },
  { word: 'Répétition', spy: ['Écho', 'Réverbération', 'Son'] },
  { word: 'Son', spy: ['Écho', 'Réverbération', 'Répétition'] },
  { word: 'Mirage', spy: ['Illusion', 'Désert'] },
  { word: 'Illusion', spy: ['Mirage', 'Désert'] },
  { word: 'Désert', spy: ['Mirage', 'Illusion'] },
  { word: 'Volcan', spy: ['Lave', 'Éruption', 'Cratère'] },
  { word: 'Lave', spy: ['Volcan', 'Éruption', 'Cratère'] },
  { word: 'Éruption', spy: ['Volcan', 'Lave', 'Cratère'] },
  { word: 'Cratère', spy: ['Volcan', 'Lave', 'Éruption'] },
  { word: 'Constellation', spy: ['Étoiles', 'Voie Lactée', 'Astérisme'] },
  { word: 'Étoiles', spy: ['Constellation', 'Voie Lactée', 'Astérisme'] },
  { word: 'Voie Lactée', spy: ['Constellation', 'Étoiles', 'Astérisme'] },
  { word: 'Astérisme', spy: ['Constellation', 'Étoiles', 'Voie Lactée'] },
  { word: 'Abysse', spy: ['Profondeur', 'Ténèbres', 'Fosse'] },
  { word: 'Profondeur', spy: ['Abysse', 'Ténèbres', 'Fosse'] },
  { word: 'Ténèbres', spy: ['Abysse', 'Profondeur', 'Fosse'] },
  { word: 'Fosse', spy: ['Abysse', 'Profondeur', 'Ténèbres'] },
  { word: 'Métamorphose', spy: ['Transformation', 'Mutation', 'Changement'] },
  { word: 'Transformation', spy: ['Métamorphose', 'Mutation', 'Changement'] },
  { word: 'Mutation', spy: ['Métamorphose', 'Transformation', 'Changement'] },
  { word: 'Changement', spy: ['Métamorphose', 'Transformation', 'Mutation'] },
  { word: 'Énigme', spy: ['Mystère', 'Secret'] },
  { word: 'Mystère', spy: ['Énigme', 'Secret'] },
  { word: 'Secret', spy: ['Énigme', 'Mystère'] },
  { word: 'Incandescence', spy: ['Lumière', 'Chaleur', 'Brillance'] },
  { word: 'Lumière', spy: ['Incandescence', 'Chaleur', 'Brillance'] },
  { word: 'Chaleur', spy: ['Incandescence', 'Lumière', 'Brillance'] },
  { word: 'Brillance', spy: ['Incandescence', 'Lumière', 'Chaleur'] },
  { word: 'Maison', spy: ['Toit', 'Porte', 'Fenêtre'] },
  { word: 'Toit', spy: ['Maison', 'Porte', 'Fenêtre'] },
  { word: 'Porte', spy: ['Maison', 'Toit', 'Fenêtre'] },
  { word: 'Fenêtre', spy: ['Maison', 'Toit', 'Porte'] },
  { word: 'Arbre', spy: ['Feuille', 'Racine', 'Branche'] },
  { word: 'Feuille', spy: ['Arbre', 'Racine', 'Branche'] },
  { word: 'Racine', spy: ['Arbre', 'Feuille', 'Branche'] },
  { word: 'Branche', spy: ['Arbre', 'Feuille', 'Racine'] },
  {
    word: 'Rivière',
    spy: ['Courant', 'Eau', 'Berge'],
  },
  {
    word: 'Courant',
    spy: ['Rivière', 'Eau', 'Berge'],
  },
  {
    word: 'Eau',
    spy: ['Rivière', 'Courant', 'Berge'],
  },
  {
    word: 'Berge',
    spy: ['Rivière', 'Courant', 'Eau'],
  },
  {
    word: 'Livre',
    spy: ['Page', 'Histoire', 'Auteur'],
  },
  {
    word: 'Page',
    spy: ['Livre', 'Histoire', 'Auteur'],
  },
  {
    word: 'Histoire',
    spy: ['Livre', 'Page', 'Auteur'],
  },
  {
    word: 'Auteur',
    spy: ['Livre', 'Page', 'Histoire'],
  },
]
export default words
